Repository UNIZAR-30246-WebEngineering/lab3-restful-ws, pull requests merged in 2021-11, with the labels that each got.

#10 Primary Goal
  README.md
Labels: enhancement

#11 Primary goal
  README.md
Labels: enhancement

#8 Secondary Goal: Support of CORS requests
  README.md
Labels: enhancement, gift

#12 Update README.md
  README.md
Labels: enhancement

#13 Primary goal
  README.md
Labels: enhancement

#14 Primary goal
  README.md
Labels: enhancement

#15 Primary goal
  README.md
Labels: enhancement

#16 Primary goal
  README.md
Labels: enhancement

#19 Primary goal
  README.md
Labels: enhancement

#21 Primar Goal
  README.md
Labels: enhancement

#20 Task 1º finished
  README.md
Labels: enhancement

#17 Primary goal
  README.md
Labels: enhancement

#22 Primary Goal
  README.md
Labels: enhancement

#4 Primary goal
  README.md
Labels: enhancement

#26 Primary goal
  README.md
Labels: enhancement

#27 Primary Goal Lab3
  README.md
Labels: enhancement

#30 solution
  README.md
Labels: enhancement

#31 docs: Add entry as finished work
  README.md
Labels: enhancement

#32 Primary Request
  README.md
Labels: enhancement

#33 Update README.md
  README.md
Labels: enhancement

#37 Primary Goal
  README.md
Labels: enhancement

#24 JWT implemented
  README.md
Labels: gift

#38 Primary Goal
  README.md
Labels: enhancement

#40 Primary goal
  README.md
Labels: enhancement

#42 Primary Goal
  README.md
Labels: enhancement

#43 Primary Goal
  README.md
Labels: enhancement
